#!/bin/bash

export WINE_DEFAULT_BRANCH="stable"
export WINE_DEFAULT_VERSION="11.0.0.0"

export WINE_PREFIXES="$HOME/.local/share/wineprefixes"


if ! [[ -v WINE_UTILS_IN_PATH ]];
then
    # This script is meant for sourcing only, thus WINE_UTILS
    # need to store ${BASH_SOURCE[0]}, not $0
    WINE_UTILS=$(realpath $(dirname ${BASH_SOURCE[0]}))

    if [[ "$WINE_UTILS" == "" ]];
    then
        echo -e "Something wrong happened setting WINE Utils in PATH."
        echo -e "This is really extrange, thus, lets see something:"
        echo -e "[DEBUG] \$0: $0, \$1: $1\n"

        exit 1
    fi

    export PATH=$WINE_UTILS:$PATH
    echo -e "'$WINE_UTILS' added temporaly to PATH.\n"

    export WINE_UTILS_IN_PATH=1
fi


if ! [[ -v BASH_HELPERS_LOADED ]];
then
    if [[ -f "$WINE_UTILS/bash_helpers" ]];
    then
        source "$WINE_UTILS/bash_helpers"
    else
        source bash_helpers

        if ! [[ "$?" == "0" ]];
        then
            echo -e "Downloading BASH helpers..."
            echo -e "---------------------------"

            URL="https://github.com/aribrew/bash_scripting"
            URL+="/raw/refs/heads/main/bash_helpers"

            curl -LO $URL

            if ! [[ "$?" == "0" ]];
            then
                echo -e "Ouch! Failed."
                exit 1
            fi

            echo -e "Done. Adding to PATH temporaly."
            
            chmod +x "$WINE_UTILS/bash_helpers"
            source "$WINE_UTILS/bash_helpers"
        fi
    fi
fi


is_wine_installation()
{
    local WINE_PATH="$1"

    echo -e "Checking for a valid WINE installation at '$WINE_PATH' ..."

    if [[ -d "$WINE_PATH" ]];
    then
        WINE_SERVER=$(find "$WINE_PATH"/** -type f -name "wineserver")

        if ! [[ "$WINE_SERVER" == "" ]];
        then
            echo -e "Seems good.\n"

            return 0
        fi
    fi

    echo -e "The wineserver executable was not found."
    echo -e "If extracting to /tmp/wine, this can be ignored.\n"

    return 1
}


is_wine_prefix()
{
    local PREFIX="$1"

    if [[ $(dirname "$PREFIX") == "." ]];
    then
        local PREFIX="$WINE_PREFIXES/$PREFIX"
    fi

    echo -e "Checking for 'dosdevices' in '$PREFIX'..."

    if [[ -d "$PREFIX" ]];
    then
        if [[ -d "$PREFIX/dosdevices" ]];
        then
            echo -e "Found. It seems a valid WINE prefix."
            return 0
        fi
    fi

    echo -e "Not found. Not a valid WINE prefix."
    return 1
}


export -f is_wine_installation
export -f is_wine_prefix
