#!/bin/bash


abort()
{
    MESSAGE=$1

    if ! [ "$MESSAGE" == "" ];
    then
        echo "$MESSAGE"
        echo ""
    fi

    exit 1
}


usage()
{
    echo "Usage: isolabel <iso path>"
    echo "Valid image types: iso, bin/cue."
    echo ""
}




if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


if ! [ -f "/usr/bin/cd-info" ];
then
    abort "Install libcdio-utils package."
fi


ISO="$1"
ISO=$(realpath "$ISO")
ISO_FILENAME=$(basename "$ISO")
FILE_EXT=$(filext "$ISO_FILENAME")


if [ "$FILE_EXT" == ".bin" ];
then
    ISO=${ISO/.bin/.cue}

elif [ "$FILE_EXT" == ".BIN" ];
then
    ISO=${ISO/.BIN/.CUE}
fi


if [[ $ISO == *.cue ]] || [[ $ISO == *.CUE ]];
then
    cd-info "$ISO" | grep -m1 "Volume" | cut -d ':' -f 2 | xargs

elif [[ $ISO == *.iso ]] || [[ $ISO == *.ISO ]];
then
    LABEL=$(iso-info -d -i "$ISO" | grep -m1 "Volume id:" | cut -d ':' -f 2 | xargs)

    if [ "$LABEL" == "" ];
    then
        LABEL=$(iso-info -d -i "$ISO" | grep -m1 "Volume" | cut -d ':' -f 2 | xargs)
    fi

    if [ "$LABEL" == "" ];
    then
        echo "UNNAMED"
    else
        echo "$LABEL"
    fi

else
    echo "UNKNOWN"
    exit 1
fi

