#!/bin/bash

SCRIPT_HOME=$(realpath $(dirname $0))


if [[ -v TERMUX_VERSION ]];
then
    "$SCRIPT_HOME/bchunk-termux" $*
else
    if ! [[ "$(which bchunk)" == "" ]];
    then
        bchunk $*
    else
        export PATH=$SCRIPT_HOME:$PATH
        
        THIS_ARCH=$(uname -m)
        BCHUNK="bchunk"

        if [[ "$THIS_ARCH" == "x86" ]];
        then
            BCHUNK+="-i386"
            
        elif [[ "$THIS_ARCH" == "x86_64" ]];
        then
            BCHUNK+="-amd64"
            
        elif [[ "$THIS_ARCH" == "aarch64" ]];
        then
            BCHUNK+="-arm64"
        else
            BCHUNK+="-armhf"
        fi

        $BCHUNK $*
    fi
fi
