#!/bin/bash

if ! [[ "$1" == "" ]] && [[ -f "$1" ]];
then
    ISO=$1
    EXTENSION=$(filext "$ISO")
    LC_EXT=$(lowercase "$EXTENSION")

    if [[ "$LC_EXT" == ".iso" ]] || [[ "$LC_EXT" == ".bin" ]];
    then
        if [[ -f "$(which /usr/bin/cd-info)" ]];
        then
            LABEL=$(iso-info -d -i "$ISO" | grep -m 1 "Volume id:")

            if [[ "$LABEL" == "" ]];
            then
                LABEL=$(iso-info -d -i "$ISO" | grep -m 1 "Volume")
            fi
        fi
    fi

    if ! [[ "$LABEL" == "" ]];
    then
        LABEL=$(echo "$LABEL" | cut -d ':' -f 2 | xargs)
        echo "$LABEL"
    else
        isoname "$ISO"
    fi
fi
