#!/bin/bash

if ! [[ "$1" == "" ]] && [[ -d "$1" ]];
then
    SCRIPT_DIR=$(realpath $(dirname $0))
    
    export PATH=$SCRIPT_DIR:$PATH

    MOUNT=$(basename "$1")

    if [[ -f "/tmp/iso/.${MOUNT}_mounted" ]];
    then
        rm -r "/tmp/iso/${MOUNT}"
        rm "/tmp/iso/.${MOUNT}_mounted"

        echo -e "ISO in '$SCRIPT_DIR' unmounted.\n"
    fi
fi
