#!/bin/bash

filext()
{
    FILE=$1
    FILE_NAME=$(basename "$1")
    FILE_EXTENSION=${FILE_NAME##*.}

    echo ".$FILE_EXTENSION"
}


lowercase()
{
    TEXT="$1"

    if ! [[ "$TEXT" == "" ]];
    then
        echo "$TEXT" | awk '{print tolower($0)}'
    fi
}


isolabel()
{
    ISO=$1
    EXTENSION=$(filext "$ISO")
    LC_EXT=$(lowercase "$EXTENSION")

    if [[ "$LC_EXT" == ".iso" ]] || [[ "$LC_EXT" == ".bin" ]];
    then
        if [[ -f "$(which /usr/bin/cd-info)" ]];
        then
            LABEL=$(iso-info -d -i "$ISO" | grep -m 1 "Volume id:")

            if [[ "$LABEL" == "" ]];
            then
                LABEL=$(iso-info -d -i "$ISO" | grep -m 1 "Volume")

                if [[ "$LABEL" == "" ]];
                then
                    echo "UNKNOWN"
                fi
            fi
            
            LABEL=$(echo "$LABEL" | cut -d ':' -f 2 | xargs)

            echo "$LABEL"
            
        else
            FILE_NAME_WEXT=$(basename "$ISO" $EXTENSION)

            if ! [[ "$FILE_NAME_WEXT" == "" ]];
            then
                ISO_LABEL=$(uppercase "$FILE_NAME_WEXT")
                ISO_LABEL=$(echo "$ISO_LABEL" | sed 's/ /_/g')

                echo "$ISO_LABEL"
            fi
        fi
    fi
}


mount()
{
    ISO=$1
    LABEL=$(isolabel "$ISO")
    MOUNT_PATH="/tmp/iso/$LABEL"

    if [[ -d "$MOUNT_PATH" ]];
    then
        echo "This ISO is already mounted in '$MOUNT_PATH'."
        echo ""
        
        exit 1
    fi
}


uppercase()
{
    TEXT=$1
    
    if ! [[ "$TEXT" == "" ]];
    then
        echo "$TEXT" | awk '{print toupper($0)}'
    fi
}




if ! [[ "$1" == "" ]] && [[ -f "$1" ]];
then
    ISO="$1"
    ISO_TYPE=$(filext "$ISO")

    if [[ "$ISO_TYPE" == ".iso" ]] || [[ "$ISO_TYPE" == ".ISO" ]];
    then
        mount "$ISO"
    fi
fi

